import type { CommandCenterSpec } from "@/lib/canvas-sdk/types";

/** Plain-language priority queue. Numbers trace back to the spoke panels they link into. */
export const fenderCommandCenter: CommandCenterSpec = {
  badge: "COMMAND CENTER · TODAY",
  title: "What do I need to worry about?",
  desc: "The highest-value moves across the 3,430 monitored electric SKUs, ranked by what they cost you while they sit open.",
  summary:
    "Portfolio Retail shows 457 of 993 active offers under MAP and 39 suppressed listings where the new offer is above Amazon's outside benchmark. AI assistants win for Fender on 73.3% of answered prompts, but beginner queries fall to 33.3%, and the sampled fender.com pages publish no machine-readable specs.",
  openByDefault: true,
  storageKey: "ifai:fender:command-center",
  items: [
    {
      id: "buybox-suppression",
      title: "39 active offers have no Featured Offer",
      why: "On 6 Oct 2026, Keepa showed 39 of 993 active offers with no Featured Offer (the Buy Box) because the new price is above Amazon's Competitive External Price. A listing can be at MAP and still be suppressed when that outside benchmark is lower. Amazon does not name the retailer. Open the row to see the Amazon listing, and a Walmart, Musician's Friend, or Guitar Center link when a page at that benchmark was found.",
      impact: "These 39 are 3.9% of active offers. MAP leakage is wider: 457 listings, averaging 16.49% under MAP and $221.96 each.",
      severity: "critical",
      spokeId: "ecommerce",
      subTab: "Suppressed",
      defaultOwner: "intofocus",
    },
    {
      id: "review-splintering",
      title: "14 partner bundle listings need catalog governance",
      why: "Separate bundle pages can fragment the shopping journey and introduce inconsistent titles, attributes, or product specifications. The action queue identifies each listing that needs a parent-child eligibility review, catalog cleanup, or seller attribution.",
      impact: "Twelve cases already have a named partner and two need seller attribution before the catalog-governance action can be assigned.",
      severity: "critical",
      spokeId: "ecommerce",
      subTab: "Catalog",
      defaultOwner: "client",
    },
    {
      id: "ai-spec-hallucination",
      title: "AI assistants are quoting specs you never published",
      why: "ChatGPT, Claude, and Perplexity can't read specs out of marketing copy, so they scrape whatever a third-party bundle page claims. That is where the wrong fingerboard radius and the phantom Acoustasonic pickup configuration come from, and shoppers are being told those are your specs.",
      impact: "Every corrected spec removes a reason for an AI engine to recommend a competitor instead.",
      severity: "critical",
      spokeId: "aeo",
      subTab: "Hallucination",
      defaultOwner: "intofocus",
    },
    {
      id: "schema-coverage",
      title: "Sampled fender.com pages publish no machine-readable specs",
      why: "A live sample found the fender.com product page only 29.2% of the time (21 of 72). Of the pages found, 0% include Schema.org additionalProperty fields such as fingerboard radius, pickup configuration, nut width, scale length, body wood, and fret count, so an AI engine has nothing authoritative to read.",
      impact: "This is the groundwork that makes the spec-hallucination fixes stick permanently.",
      severity: "high",
      spokeId: "specs",
      subTab: "Schema",
      defaultOwner: "intofocus",
    },
    {
      id: "map-leakage",
      title: "Discounted bundles are dragging your prices down everywhere",
      why: "457 of 993 active offers are priced under the stored MAP. It is the highest-volume Portfolio Retail issue, ahead of the 39 suppressed listings.",
      impact: "The average gap is 16.49% of MAP, $221.96 per listing, $101,434.60 combined.",
      severity: "high",
      spokeId: "ecommerce",
      subTab: "MAP",
      defaultOwner: "client",
    },
    {
      id: "midrange-losses",
      title: "You lose head-to-head recommendations at $600–$1,200",
      why: "Live simulations put Yamaha at 66.7% share of voice in the beginner category, and Taylor and PRS tied at 15.4% each in acoustics. Fender still leads acoustics at 61.5% and amps at 100% of 9 resolved prompts, but the beginner gap is 50 points.",
      impact: "This is the bracket where recovered visibility converts fastest.",
      severity: "high",
      spokeId: "competitors",
      subTab: "Battlecards",
      defaultOwner: "intofocus",
    },
    {
      id: "aplus-tables",
      title: "14 catalog lines still need an A+ comparison matrix",
      why: "Amazon's A+ comparison tables are parsed directly by Rufus and by the frontier AI models. The recommended 4-column matrix (Squier Classic Vibe, Player II, American Performer, American Pro II) is how you define the step up yourself. On the live sample, Amazon product fields are already 93.3% complete; fender.com structured specs are the gap.",
      severity: "moderate",
      spokeId: "specs",
      subTab: "A+",
      defaultOwner: "intofocus",
    },
  ],
};
