import type { CommandCenterSpec } from "@/lib/canvas-sdk/types";

/** Plain-language priority queue. Numbers trace back to the spoke panels they link into. */
export const fenderCommandCenter: CommandCenterSpec = {
  badge: "COMMAND CENTER · TODAY",
  title: "What do I need to worry about?",
  desc: "The highest-value moves across the 124 monitored SKUs, ranked by what they cost you while they sit open.",
  summary:
    "Amazon is hiding your buy button on roughly a third of your listings, and AI shopping assistants are reading the wrong specs off bundle pages you do not control. Both trace back to the same root cause: your catalog is split across listings you have not consolidated. Fix the catalog and the other six items get easier.",
  openByDefault: true,
  storageKey: "ifai:fender:command-center",
  items: [
    {
      id: "buybox-suppression",
      title: "Amazon is hiding your buy button on 18% of listings",
      why: "When a partner prices a bundle below your listed price anywhere else on the web, Amazon removes the one-click buy button entirely and shows 'Available from these sellers' instead. Shoppers who hit that page convert about 65% less often. Fourteen of your core guitar and amp listings are in this state right now.",
      impact: "Restoring the buy button on the 14 flagged listings is the single fastest revenue recovery on this board.",
      severity: "critical",
      spokeId: "ecommerce",
      subTab: "Flagged ASINs",
      defaultOwner: "intofocus",
    },
    {
      id: "review-splintering",
      title: "2,420 customer reviews are stranded on the wrong pages",
      why: "Every time a partner lists a Strat bundled with a gig bag, they create a separate product page — and the reviews customers leave there never reach your main listing. Amazon hands its 'Overall Pick' badge to whoever has the most reviews, so that badge is currently going to PRS and Yamaha instead of you.",
      impact: "Nesting partner bundles under your parent listings pools the reviews back without costing partners a single sale.",
      severity: "critical",
      spokeId: "ecommerce",
      subTab: "Catalog",
      defaultOwner: "client",
    },
    {
      id: "ai-spec-hallucination",
      title: "AI assistants are quoting specs you never published",
      why: "ChatGPT, Claude and Perplexity cannot read specs out of marketing copy, so they scrape whatever a third-party bundle page claims. That is where the wrong fingerboard radius and the phantom Acoustasonic pickup configuration are coming from — and shoppers are being told those are your specs.",
      impact: "Every corrected spec removes a reason for an AI engine to recommend a competitor instead.",
      severity: "critical",
      spokeId: "aeo",
      subTab: "Hallucination",
      defaultOwner: "intofocus",
    },
    {
      id: "schema-coverage",
      title: "Two-thirds of your catalog is invisible to AI crawlers",
      why: "Only 34% of your 124 SKUs publish machine-readable specs. For the rest, an AI engine asked 'which guitar has a 9.5 inch radius' has nothing authoritative to read from fender.com and falls back to guessing or to a reseller's page.",
      impact: "This is the groundwork that makes the spec-hallucination fixes stick permanently.",
      severity: "high",
      spokeId: "specs",
      subTab: "Schema",
      defaultOwner: "intofocus",
    },
    {
      id: "map-leakage",
      title: "Discounted bundles are dragging your prices down everywhere",
      why: "A partner bundles a $849 Strat with a $15 gig bag and lists the pair at $808. Pricing bots on Walmart and Reverb see that number and match it within hours, and Amazon then reads those cheaper listings as a reason to suppress your buy button. One bundle sets off the whole chain.",
      impact: "33 listings across three marketplaces are currently drifting an average of $45 below your set price.",
      severity: "high",
      spokeId: "ecommerce",
      subTab: "MAP",
      defaultOwner: "client",
    },
    {
      id: "midrange-losses",
      title: "You lose head-to-head recommendations at $600–$1,200",
      why: "In the price bracket where most first serious guitar purchases happen, AI engines recommend PRS SE, Taylor and Yamaha over Fender — not on heritage, but because those brands publish clean specs and pooled reviews that a model can cite as fact. Heritage recognition does not help when the model needs a number.",
      impact: "This is the bracket where recovered visibility converts fastest.",
      severity: "high",
      spokeId: "competitors",
      subTab: "Battlecards",
      defaultOwner: "intofocus",
    },
    {
      id: "aplus-tables",
      title: "78% of product lines have no comparison table",
      why: "Amazon's A+ comparison tables are parsed directly by Rufus and by the frontier AI models. Without one, you have no say in how a shopper is shown the step up from Squier to Player to American Pro — a competitor's table frames that decision instead.",
      severity: "moderate",
      spokeId: "specs",
      subTab: "A+",
      defaultOwner: "intofocus",
    },
  ],
};
