import { spokeData, tourSteps } from "@/components/v3/spoke-data";
import { defineCanvas } from "@/lib/canvas-sdk";

const FOCUS_TARGETS = {
  hub: { x: 800, y: 500 },
  aeo: { x: 440, y: 320 },
  "aeo:prompts": { x: 240, y: 200 },
  "aeo:citations": { x: 180, y: 360 },
  "aeo:hallucinations": { x: 260, y: 480 },
  ecommerce: { x: 1160, y: 320 },
  "ecommerce:buybox": { x: 1360, y: 200 },
  "ecommerce:asins": { x: 1420, y: 360 },
  "ecommerce:pricing": { x: 1340, y: 480 },
  specs: { x: 440, y: 680 },
  "specs:schema": { x: 230, y: 720 },
  "specs:matrix": { x: 320, y: 870 },
  competitors: { x: 1160, y: 680 },
  "competitors:taylor": { x: 1370, y: 720 },
  "competitors:amps": { x: 1280, y: 870 },
  suggestions: { x: 800, y: 820 },
  roadmap: { x: 800, y: 180 },
};

export const fenderCanvasSpec = defineCanvas({
  brand: {
    name: "Fender Brand Intelligence Canvas",
    subtitle: "FMIC Omnichannel Intelligence · 124 Monitored ASINs",
    logoSrc: "/icon.png",
    badge: "Portfolio View",
  },
  filters: [
    { value: "all", label: "Entire Brand Portfolio (124 SKUs)", target: "overview" },
    { value: "electrics", label: "Electric Division (Strat, Tele, Jazzmaster)", target: "aeo" },
    {
      value: "acoustics",
      label: "Acoustic & Hybrids (Acoustasonic, Paramount)",
      target: "competitors",
    },
    { value: "bass", label: "Bass Division (Precision, Jazz Bass)", target: "specs" },
    { value: "amps", label: "Amps & Digital Audio (Tone Master, Mustang)", target: "aeo" },
    { value: "squier", label: "Squier Entry Tier (Affinity, Classic Vibe)", target: "ecommerce" },
  ],
  tickers: [
    {
      id: "buybox",
      tone: "danger",
      icon: "pulse",
      spokeId: "ecommerce",
      subTab: "buy box",
      label: (
        <>
          Buy Box: <strong>68%</strong> (14 ASINs Suppressed / 3P Split)
        </>
      ),
    },
    {
      id: "aeo",
      tone: "warning",
      icon: "sparkles",
      spokeId: "aeo",
      subTab: "dual-index",
      label: (
        <>
          AEO Scan: <strong>41</strong> · Readiness: <strong>52%</strong>
        </>
      ),
    },
    {
      id: "opportunity",
      tone: "success",
      icon: "trending",
      spokeId: "suggestions",
      subTab: "roi",
      label: (
        <>
          Lift: <strong>+$680K Pilot</strong> (+$28.4M Enterprise)
        </>
      ),
    },
  ],
  search: {
    placeholder: "Search line, node, ASIN...",
    matchers: [
      { keywords: ["buy box", "asin", "retail", "amazon", "walmart", "reverb"], spokeId: "ecommerce" },
      { keywords: ["aeo", "prompt", "citation", "ai", "readiness"], spokeId: "aeo" },
      { keywords: ["spec", "schema", "matrix"], spokeId: "specs" },
      { keywords: ["competitor", "taylor", "prs", "boss"], spokeId: "competitors" },
      { keywords: ["fix", "suggestion", "revenue", "roi", "enterprise", "pilot"], spokeId: "suggestions" },
      { keywords: ["roadmap", "timeline", "90"], spokeId: "roadmap" },
      { keywords: ["briefing", "hub", "portfolio", "ceo"], spokeId: "hub" },
    ],
  },
  legend: [
    { status: "danger", label: "Critical / Buy Box Loss" },
    { status: "warning", label: "At Risk / Spec Drift" },
    { status: "success", label: "On Track / Lift Target" },
  ],
  edges: [
    { x1: 800, y1: 500, x2: 440, y2: 320, kind: "active" },
    { x1: 800, y1: 500, x2: 1160, y2: 320, kind: "critical" },
    { x1: 800, y1: 500, x2: 440, y2: 680, kind: "warning" },
    { x1: 800, y1: 500, x2: 1160, y2: 680, kind: "active" },
    { x1: 800, y1: 500, x2: 800, y2: 180, kind: "active" },
    { x1: 800, y1: 500, x2: 800, y2: 820, kind: "active" },
    { x1: 440, y1: 320, x2: 240, y2: 200 },
    { x1: 440, y1: 320, x2: 180, y2: 360 },
    { x1: 440, y1: 320, x2: 260, y2: 480 },
    { x1: 1160, y1: 320, x2: 1360, y2: 200, kind: "critical" },
    { x1: 1160, y1: 320, x2: 1420, y2: 360, kind: "critical" },
    { x1: 1160, y1: 320, x2: 1340, y2: 480 },
    { x1: 440, y1: 680, x2: 230, y2: 720 },
    { x1: 440, y1: 680, x2: 320, y2: 870 },
    { x1: 1160, y1: 680, x2: 1370, y2: 720 },
    { x1: 1160, y1: 680, x2: 1280, y2: 870 },
  ],
  paths: [{ d: "M 440 320 Q 800 310 1160 320" }],
  badges: [
    {
      x: 800,
      y: 315,
      width: 280,
      height: 24,
      text: "🚨 3P RETAIL DRIFT DILUTING BRAND AI CITATIONS",
    },
  ],
  nodes: [
    {
      id: "sat-prompts",
      x: 240,
      y: 200,
      r: 52,
      status: "danger",
      title: "PROMPTS",
      stats: ["32%"],
      meta: "Brand SOV",
      spokeId: "aeo",
      subTab: "prompts",
      tooltip: {
        title: "Brand Prompt Tracking",
        desc: "Tracked 100 benchmark prompts across 5 AI engines: 32% general SOV. Controllable readiness 52%.",
      },
    },
    {
      id: "sat-citations",
      x: 180,
      y: 360,
      r: 52,
      status: "danger",
      title: "CITATIONS",
      stats: ["12% DTC", "31% Reddit"],
      spokeId: "aeo",
      subTab: "citations",
      tooltip: {
        title: "Citation Distribution",
        desc: "Reddit & Amazon represent 55% of all citations; DTC contributes only 12%.",
      },
    },
    {
      id: "sat-drift",
      x: 260,
      y: 480,
      r: 50,
      status: "warning",
      title: "AI DRIFT",
      stats: ["14 Spec Bugs"],
      meta: "Woods / Radius",
      spokeId: "aeo",
      subTab: "hallucinations",
      tooltip: {
        title: "Spec Hallucinations",
        desc: "14 catalog spec drift errors across Acoustasonic, Player II, and Tone Master.",
      },
    },
    {
      id: "sat-buybox",
      x: 1360,
      y: 200,
      r: 54,
      status: "danger",
      title: "BUY BOX",
      stats: ["68%"],
      meta: "124 SKUs",
      spokeId: "ecommerce",
      subTab: "buybox",
      tooltip: {
        title: "Portfolio Buy Box",
        desc: "Catalog-wide Buy Box at 68% across 124 SKUs due to 15 unauthorized 3P merchants.",
      },
    },
    {
      id: "sat-asin",
      x: 1420,
      y: 360,
      r: 52,
      status: "warning",
      title: "ASIN SPLIT",
      stats: ["14 Flagged"],
      meta: "2.4K Reviews",
      spokeId: "ecommerce",
      subTab: "asins",
      tooltip: {
        title: "Portfolio ASIN Sprawl",
        desc: "14 flagged 3P bundle listings splitting 2,420+ reviews across Strat, Tele, Acoustasonic.",
      },
    },
    {
      id: "sat-map",
      x: 1340,
      y: 480,
      r: 50,
      status: "danger",
      title: "MAP DRIFT",
      stats: ["-$52 avg"],
      meta: "15 Sellers",
      spokeId: "ecommerce",
      subTab: "pricing",
      tooltip: {
        title: "MAP Violations",
        desc: "Average $52 3P price undercut on Amazon triggering AI crawler omission.",
      },
    },
    {
      id: "sat-schema",
      x: 230,
      y: 720,
      r: 50,
      status: "warning",
      title: "SCHEMA.ORG",
      stats: ["34% Sync"],
      meta: "14 Fields Missing",
      spokeId: "specs",
      subTab: "schema",
      tooltip: {
        title: "Brand Schema Coverage",
        desc: "Only 34% of catalog SKUs have structured technical specifications in JSON-LD.",
      },
    },
    {
      id: "sat-tables",
      x: 320,
      y: 870,
      r: 48,
      status: "warning",
      title: "A+ TABLES",
      stats: ["78% Gap"],
      meta: "14 of 18 Lines",
      spokeId: "specs",
      subTab: "matrix",
      tooltip: {
        title: "A+ Comparison Matrices",
        desc: "78% of catalog product pages missing structured comparison grids.",
      },
    },
    {
      id: "sat-taylor",
      x: 1370,
      y: 720,
      r: 51,
      status: "danger",
      title: "TAYLOR / PRS",
      stats: ["58% SOV"],
      meta: "Acoustics/SE",
      spokeId: "competitors",
      subTab: "taylor",
      tooltip: {
        title: "Taylor & PRS Threat",
        desc: "Taylor controls 58% travel/acoustic citations; PRS SE controls 34% mid-tier electrics.",
      },
    },
    {
      id: "sat-amps",
      x: 1280,
      y: 870,
      r: 48,
      status: "warning",
      title: "BOSS / SPARK",
      stats: ["62% SOV"],
      meta: "Digital Amps",
      spokeId: "competitors",
      subTab: "amps",
      tooltip: {
        title: "Amp & Entry Competitors",
        desc: "Boss Katana, Spark MINI, and Yamaha Pacifica dominating entry recommendations.",
      },
    },
    {
      id: "spoke-aeo",
      x: 440,
      y: 320,
      r: 84,
      status: "danger",
      title: "BRAND AEO",
      titleSize: 14.5,
      stats: ["41/100", "−11 pts"],
      meta: "Readiness 52%",
      spokeId: "aeo",
      tooltip: {
        title: "Brand AEO Visibility",
        desc: "Brand Visibility Score: 41/100 · Controllable Readiness: 52%. Click to explore 100 simulations.",
      },
    },
    {
      id: "spoke-retail",
      x: 1160,
      y: 320,
      r: 84,
      status: "danger",
      title: "PORTFOLIO RETAIL",
      titleSize: 13.5,
      stats: ["68%", "14 Flagged"],
      meta: "124 ASINs · Buy Box",
      spokeId: "ecommerce",
      tooltip: {
        title: "Portfolio E-Commerce",
        desc: "Buy Box 68% · 14 flagged ASINs. 18% suppressed, 14% lost to 3P bundles.",
      },
    },
    {
      id: "spoke-specs",
      x: 440,
      y: 680,
      r: 78,
      status: "warning",
      title: "SPEC READINESS",
      titleSize: 13.5,
      stats: ["34%", "14 Gaps"],
      meta: "Schema & A+ Grids",
      spokeId: "specs",
      tooltip: {
        title: "Catalog Spec Readiness",
        desc: "34% Schema.org completeness. 14 of 18 key catalog lines lack structured comparison grids.",
      },
    },
    {
      id: "spoke-competitors",
      x: 1160,
      y: 680,
      r: 78,
      status: "danger",
      title: "COMPETITIVE RADAR",
      titleSize: 13,
      stats: ["6 Rivals", "-29% Gap"],
      meta: "Taylor · PRS · Boss · Yamaha",
      spokeId: "competitors",
      tooltip: {
        title: "Brand Competitive Radar",
        desc: "Benchmarking against Gibson/Epiphone, Taylor, PRS, Ibanez, Boss, and Yamaha.",
      },
    },
    {
      id: "spoke-fixes",
      x: 800,
      y: 820,
      r: 74,
      status: "success",
      title: "BRAND FIXES",
      titleSize: 14,
      stats: ["18 Fixes", "+$680K"],
      meta: "Pilot / Enterprise",
      spokeId: "suggestions",
      tooltip: {
        title: "Portfolio Suggestion Engine",
        desc: "18 high-impact brand interventions: +$680k Pilot / +$28.4M Enterprise.",
      },
    },
    {
      id: "spoke-roadmap",
      x: 800,
      y: 180,
      r: 70,
      status: "success",
      title: "ROADMAP",
      titleSize: 14,
      stats: ["90 Days", "88/100"],
      meta: "Target Index",
      spokeId: "roadmap",
      tooltip: {
        title: "Executive Brand Roadmap",
        desc: "30-60-90 Day brand transformation to lift overall AEO index from 41 to 88.",
      },
    },
    {
      id: "hub",
      x: 800,
      y: 500,
      r: 98,
      status: "danger",
      variant: "hub",
      title: "BRAND PORTFOLIO",
      stats: ["41%", "4 Anomalies"],
      meta: "124 SKUs · 5 Divisions",
      spokeId: "hub",
      tooltip: {
        title: "Master Brand Portfolio Core",
        desc: "Click to open Master Executive Briefing, Multi-Division Scorecard & Enterprise ROI",
      },
    },
  ],
  spokes: spokeData,
  focusTargets: FOCUS_TARGETS,
  tour: tourSteps,
});
