import type { CanvasNode } from "@/lib/canvas-sdk/types";
import { FENDER_METRICS } from "@/components/v3/fender-metrics";

export const fenderStaticNodes: CanvasNode[] = [
    {
      id: "sat-prompts",
      x: 240,
      y: 200,
      r: 52,
      status: "danger",
      title: "102 Sims",
      stats: ["34 Prompts x 3 Engines", "73% Win (of Answered)"],
      meta: "ChatGPT · Perplexity · Gemini",
      spokeId: "aeo",
      subTab: "simulations",
      tooltip: {"title": "AI Simulation Battery (Live Run)", "desc": "34 prompts ran across ChatGPT, Perplexity, and Gemini through the live AI-Search API, for 102 calls in total. Of 75 answered calls (27 ChatGPT/Perplexity timeouts excluded): 55 Fender/Squier wins (73.3%), 20 competitor wins (26.7%), 4 unclear, and 2 confirmed spec hallucinations."},
    },
    {
      id: "sat-citations",
      x: 180,
      y: 360,
      r: 52,
      status: "danger",
      title: "Citations",
      stats: ["Fender/DTC 50%", "Guitar Press 28%"],
      meta: "Reddit 1% · Amazon 1% (of 74 cited answers)",
      spokeId: "aeo",
      subTab: "citation",
      tooltip: {"title": "AI Citation Ecosystem (34-Prompt Battery)", "desc": "Across 74 answered calls with citations: fender.com or other official Fender pages appeared in 37 (50%), third-party guitar press (Guitar World, MusicRadar, Premier Guitar, and others) in 21 (28.4%), Reddit in 1 (1.4%), and Amazon in 1 (1.4%). The sample is one 34-prompt run, not a full historical average."},
    },
    {
      id: "sat-drift",
      x: 260,
      y: 480,
      r: 52,
      status: "warning",
      title: "AI Drift",
      stats: [`${FENDER_METRICS.confirmedHallucinations.value} Confirmed Hallucinations`, "Mustang Micro Tubes"],
      meta: "of 6 hallucination-risk answers received",
      spokeId: "aeo",
      subTab: "hallucination",
      tooltip: {"title": "Detected Spec Hallucinations (34-Prompt Battery)", "desc": "The run flagged 2 of 6 answered hallucination-risk prompts: Perplexity and Gemini both incorrectly implied that the Fender Mustang Micro, a headphone amp, has vacuum tube circuitry. The Acoustasonic humbucker and Player II 12in radius checks did not reproduce in this run. ChatGPT timed out on those prompts, so they went untested this cycle."},
    },
    {
      id: "sat-buybox",
      x: 1360,
      y: 200,
      r: 54,
      status: "danger",
      title: "Buy Box",
      stats: [`${FENDER_METRICS.buyBoxRetention.value} 1P`, "92.6% Unk"],
      meta: "993 Active Offers",
      spokeId: "ecommerce",
      subTab: "flagged",
      tooltip: {"title": "Buy Box (Active Offers)", "desc": "Amazon 1P owns the Buy Box on 7.4% of 993 active listings. Seller data for the other 92.6% is not yet harvested, and there are 0% confirmed 3P wins."},
    },
    {
      id: "sat-asin",
      x: 1420,
      y: 360,
      r: 54,
      status: "warning",
      title: "ASIN Split",
      stats: [
        `${FENDER_METRICS.flaggedAsins.value} Bundles`,
        `${FENDER_METRICS.strandedReviews.value} Reviews`,
      ],
      meta: "Austin Bazaar / GearTree",
      spokeId: "ecommerce",
      subTab: "catalog",
      tooltip: {"title": "Splintered Bundle ASINs", "desc": "Key partners Austin Bazaar and GearTree hold Brand Registry bundle rights. Splintered reviews forfeit Amazon's Overall Pick badge."},
    },
    {
      id: "sat-map",
      x: 1340,
      y: 480,
      r: 52,
      status: "danger",
      title: "MAP Leakage",
      stats: [
        "-$39.21 Avg",
        `${FENDER_METRICS.flaggedAsins.value} ASINs`,
      ],
      meta: "Amazon · Reverb · Walmart",
      spokeId: "ecommerce",
      subTab: "map",
      tooltip: {"title": "Cross-Marketplace MAP Leakage", "desc": "Starter kit bundles sidestep standalone MAP, which prompts automated scrapers on Reverb and Walmart to undercut the price."},
    },
    {
      id: "sat-schema",
      x: 230,
      y: 720,
      r: 50,
      status: "danger",
      title: "Schema.org",
      stats: ["0% Specs", "62 Checked"],
      meta: "additionalProperty Missing",
      spokeId: "specs",
      subTab: "schema",
      tooltip: {"title": "Schema.org Structured Data (Live Sample)", "desc": "Live batch check (19 of ~993 SKUs so far): site search found a fender.com product page only 36.8% of the time (7/19). None of those 7 pages has an additionalProperty JSON-LD field, so AI engines have no machine-readable nut width, fingerboard radius, or pickup configuration to read. The specs exist only as human-readable HTML tables."},
    },
    {
      id: "sat-tables",
      x: 320,
      y: 870,
      r: 48,
      status: "warning",
      title: "A+ Tables",
      stats: ["93.3% Amazon", "62 Checked"],
      meta: "Amazon Field Completeness (Live)",
      spokeId: "specs",
      subTab: "a+",
      tooltip: {"title": "Amazon Structured Field Completeness (Live Sample)", "desc": "Live batch check (19 of ~993 SKUs so far): Amazon product_details fields such as body and neck material, pickup configuration, bridge type, scale length, and dimensions average 97.2% complete. Amazon-side data is strong; fender.com structured data is the real gap."},
    },
    {
      id: "sat-taylor",
      x: 1370,
      y: 720,
      r: 51,
      status: "warning",
      title: "Taylor / PRS",
      stats: ["15.4% Taylor", "15.4% PRS"],
      meta: "Acoustics Category (Live SOV)",
      spokeId: "competitors",
      subTab: "battlecards",
      tooltip: {"title": "Taylor and PRS Category Battles (Live AI Simulation Data)", "desc": "Live simulation SOV in the acoustics category: Taylor and PRS are tied at 15.4% each, and Fender/Squier still leads at 61.5% of resolved acoustics simulations. Earlier 58% and 34% figures were unsourced and have been retired."},
    },
    {
      id: "sat-amps",
      x: 1280,
      y: 870,
      r: 48,
      status: "warning",
      title: "Amps Category",
      stats: ["100% Fender", "9 of 9 Sims"],
      meta: "No Competitor Wins (Live)",
      spokeId: "competitors",
      subTab: "head-to-head",
      tooltip: {"title": "Digital Amp Ecosystem (Live AI Simulation Data)", "desc": "Live simulation data shows Fender/Squier winning 100% of resolved amps-category AI prompts (9 of 9). The current sample has no confirmed Boss Katana or Positive Grid Spark wins. An earlier 62% SOV claim was unsourced and has been retired."},
    },
    {
      id: "spoke-aeo",
      x: 440,
      y: 320,
      r: 86,
      status: "danger",
      title: "AI Search Visibility",
      titleSize: 14.5,
      stats: [`${FENDER_METRICS.overallAiWinRate.value} Win`, "102 Sims"],
      meta: `Weakest: Beginner ${FENDER_METRICS.beginnerAiWinRate.value}`,
      spokeId: "aeo",
      tooltip: {"title": "AI Search Visibility & Simulations (Live Data)", "desc": "AI win rate: 73.3% of 75 resolved simulations (55 Fender/Squier wins, 27 timeouts excluded). The weakest category is Beginner Electric Guitars at 33.3%. Click to inspect all 102 simulations. Earlier 62 Scan and 42% Readiness figures were unvalidated placeholders and have been retired."},
    },
    {
      id: "spoke-retail",
      x: 1160,
      y: 320,
      r: 86,
      status: "danger",
      title: "Portfolio Retail",
      titleSize: 13.5,
      stats: [`${FENDER_METRICS.buyBoxRetention.value} 1P`, "993 Active"],
      meta: "92.6% Unharvested · 993 Sample",
      spokeId: "ecommerce",
      tooltip: {"title": "Portfolio Retail & Brand Registry", "desc": "Buy Box: 7.4% 1P of 993 active offers (2,437 SKUs unharvested or without an active offer). Covers Brand Registry consolidation with Austin Bazaar and GearTree across the monitored ASIN sample."},
    },
    {
      id: "spoke-specs",
      x: 440,
      y: 680,
      r: 78,
      status: "warning",
      title: "AI Readiness",
      titleSize: 13.5,
      stats: [
        `${FENDER_METRICS.fenderFindability.value} Found`,
        `${FENDER_METRICS.machineReadableSpecs.value} Specs`,
      ],
      meta: "Live Sample: 62 of 993",
      spokeId: "specs",
      tooltip: {"title": "AI Readiness: Product Specs (Live Sample, Growing Hourly)", "desc": "Live batch check of 72 of ~993 active-offer SKUs so far. Site search found a fender.com product page only 29.2% of the time (21 of 72), and none of the pages found have Schema.org additionalProperty spec fields (0%). Amazon-side structured fields average 91.7% complete. This bubble previously showed an unsourced 34% completeness claim. The fender_spec_readiness_audit wrench now computes it and refreshes it hourly."},
    },
    {
      id: "spoke-competitors",
      x: 1160,
      y: 680,
      r: 78,
      status: "danger",
      title: "Competitive Radar",
      titleSize: 13,
      stats: ["Yamaha 66.7%", "5 Rivals (Live)"],
      meta: "Beginner Category Gap",
      spokeId: "competitors",
      tooltip: {"title": "Competitive Radar", "desc": "Live citation share from AI simulations: Yamaha holds 66.7% SOV in the beginner category and 25.0% in basses, Taylor and PRS are tied at 15.4% in acoustics, and PRS holds 12.5% in electrics. Fender/Squier wins the outright majority of resolved simulations overall."},
    },
    {
      id: "spoke-fixes",
      x: 800,
      y: 180,
      r: 74,
      status: "success",
      title: "Action Items",
      titleSize: 14,
      stats: [
        `${FENDER_METRICS.prioritizedFixes.value} Actions`,
        FENDER_METRICS.phaseOneLift.value,
      ],
      meta: "Pilot ➔ $38M to $62M Ent.",
      spokeId: "suggestions",
      tooltip: {"title": "Action Items", "desc": "18 high-impact brand interventions. Compare the Phase 1 Quick-Win ($680K) with the full enterprise portfolio potential ($38M to $62M GMV)."},
    },
    {
      id: "spoke-roadmap",
      x: 800,
      y: 820,
      r: 74,
      status: "success",
      title: "Strategy Roadmap",
      titleSize: 14,
      stats: ["90 Days", "3 Phases"],
      meta: "Buy Box & AI Search Visibility",
      spokeId: "roadmap",
      tooltip: {
        title: "90-Day Portfolio Roadmap",
        desc: "A phased 30-60-90 day plan with live baselines (73.3% AI win rate, 7.4% Buy Box) and analyst-estimated targets toward 95% Buy Box retention.",
      },
    },
    {
      id: "hub",
      x: 800,
      y: 500,
      r: 98,
      status: "danger",
      variant: "hub",
      title: "Brand Portfolio",
      stats: [],
      logoSrc: "/image.png",
      meta: "Click for Master View",
      spokeId: "hub",
      tooltip: {"title": "Brand Portfolio Overview", "desc": "Click to open the portfolio overview: 5 brand divisions, the executive briefing, and enterprise commercial sizing."},
    },
];
