import type { CanvasNode } from "@/lib/canvas-sdk/types";
import { FENDER_METRICS } from "@/components/v3/fender-metrics";
import { retailBubbleFaces } from "@/lib/fender-canvas/portfolio-retail-display";

const retailFaces = retailBubbleFaces({ phase: "loading" });

export const fenderStaticNodes: CanvasNode[] = [
    {
      id: "sat-prompts",
      x: 240,
      y: 200,
      r: 52,
      status: "danger",
      title: "102 Sims",
      stats: ["34 Prompts x 3 Engines", "73% Win (of Answered)"],
      meta: "ChatGPT · Perplexity · Gemini",
      spokeId: "aeo",
      subTab: "simulations",
      tooltip: {"title": "AI Simulation Battery", "desc": "34 prompts ran across ChatGPT, Perplexity, and Gemini through the AI-Search API, for 102 calls in total. Of 75 answered calls (27 ChatGPT/Perplexity timeouts excluded): 55 Fender/Squier wins (73.3%), 20 competitor wins (26.7%), 4 unclear, and 2 confirmed spec hallucinations."},
    },
    {
      id: "sat-citations",
      x: 180,
      y: 360,
      r: 52,
      status: "danger",
      title: "Citations",
      stats: ["Fender/DTC 50%", "Guitar Press 28%"],
      meta: "Reddit 1% · Amazon 1% (of 74 cited answers)",
      spokeId: "aeo",
      subTab: "citation",
      tooltip: {"title": "AI Citation Ecosystem (34-Prompt Battery)", "desc": "Across 74 answered calls with citations: fender.com or other official Fender pages appeared in 37 (50%), third-party guitar press (Guitar World, MusicRadar, Premier Guitar, and others) in 21 (28.4%), Reddit in 1 (1.4%), and Amazon in 1 (1.4%)."},
    },
    {
      id: "sat-drift",
      x: 260,
      y: 480,
      r: 52,
      status: "warning",
      title: "AI Drift",
      stats: [`${FENDER_METRICS.confirmedHallucinations.value} Confirmed Hallucinations`, "Stored root causes"],
      meta: "See the hallucination tab",
      spokeId: "aeo",
      subTab: "hallucination",
      tooltip: {"title": "Detected Spec Hallucinations", "desc": "Flagged simulation rows and their stored root causes are listed on the hallucination tab."},
    },
    {
      id: "sat-buybox",
      x: 1360,
      y: 200,
      r: 54,
      spokeId: "ecommerce",
      ...retailFaces.suppressed,
    },
    {
      id: "sat-asin",
      x: 1420,
      y: 360,
      r: 54,
      spokeId: "ecommerce",
      ...retailFaces.catalog,
    },
    {
      id: "sat-map",
      x: 1340,
      y: 480,
      r: 60,
      spokeId: "ecommerce",
      ...retailFaces.map,
    },
    {
      id: "sat-schema",
      x: 230,
      y: 720,
      r: 50,
      status: "danger",
      title: "Schema.org",
      stats: ["0% Specs", "62 Checked"],
      meta: "additionalProperty Missing",
      spokeId: "specs",
      subTab: "schema",
      tooltip: {"title": "Schema.org Structured Data", "desc": "Across 19 SKUs, site search found a fender.com product page only 36.8% of the time (7/19). None of those 7 pages has an additionalProperty JSON-LD field, so AI engines have no machine-readable nut width, fingerboard radius, or pickup configuration to read. The specs exist only as human-readable HTML tables."},
    },
    {
      id: "sat-tables",
      x: 320,
      y: 870,
      r: 48,
      status: "warning",
      title: "A+ Tables",
      stats: ["93.3% Amazon", "62 Checked"],
      meta: "Amazon Field Completeness",
      spokeId: "specs",
      subTab: "a+",
      tooltip: {"title": "Amazon Structured Field Completeness", "desc": "Across 19 SKUs, Amazon product_details fields such as body and neck material, pickup configuration, bridge type, scale length, and dimensions average 97.2% complete. Amazon-side data is strong; fender.com structured data is the real gap."},
    },
    {
      id: "sat-taylor",
      x: 1370,
      y: 720,
      r: 51,
      status: "warning",
      title: "Taylor / PRS",
      stats: ["15.4% Taylor", "15.4% PRS"],
      meta: "Acoustics Category SOV",
      spokeId: "competitors",
      subTab: "battlecards",
      tooltip: {"title": "Taylor and PRS Category Battles", "desc": "Simulation SOV in the acoustics category: Taylor and PRS are tied at 15.4% each, and Fender/Squier still leads at 61.5% of resolved acoustics simulations."},
    },
    {
      id: "sat-amps",
      x: 1280,
      y: 870,
      r: 48,
      status: "warning",
      title: "Amps Category",
      stats: ["100% Fender", "9 of 9 Sims"],
      meta: "No Competitor Wins",
      spokeId: "competitors",
      subTab: "head-to-head",
      tooltip: {"title": "Digital Amp Ecosystem", "desc": "Simulation data shows Fender/Squier winning 100% of resolved amps-category AI prompts (9 of 9). There are no confirmed Boss Katana or Positive Grid Spark wins."},
    },
    {
      id: "spoke-aeo",
      x: 440,
      y: 320,
      r: 86,
      status: "danger",
      title: "AI Search Visibility",
      titleSize: 14.5,
      stats: [`${FENDER_METRICS.overallAiWinRate.value} Win`, "102 Sims"],
      meta: `Weakest: Beginner ${FENDER_METRICS.beginnerAiWinRate.value}`,
      spokeId: "aeo",
      tooltip: {"title": "AI Search Visibility & Simulations", "desc": "AI win rate: 73.3% of 75 resolved simulations (55 Fender/Squier wins, 27 timeouts excluded). The weakest category is Beginner Electric Guitars at 33.3%. Click to inspect all 102 simulations."},
    },
    {
      id: "spoke-retail",
      x: 1160,
      y: 320,
      r: 96,
      titleSize: 13.5,
      spokeId: "ecommerce",
      ...retailFaces.main,
    },
    {
      id: "spoke-specs",
      x: 440,
      y: 680,
      r: 78,
      status: "warning",
      title: "AI Readiness",
      titleSize: 13.5,
      stats: [
        `${FENDER_METRICS.fenderFindability.value} Found`,
        `${FENDER_METRICS.machineReadableSpecs.value} Specs`,
      ],
      meta: "Spec read",
      spokeId: "specs",
      tooltip: {"title": "AI Readiness: Product Specs", "desc": "Site search found a fender.com product page only 29.2% of the time (21 of 72), and none of the pages found have Schema.org additionalProperty spec fields (0%). Amazon-side structured fields average 91.7% complete."},
    },
    {
      id: "spoke-competitors",
      x: 1160,
      y: 680,
      r: 78,
      status: "danger",
      title: "Competitive Radar",
      titleSize: 13,
      stats: ["Yamaha 66.7%", "5 Rivals"],
      meta: "Beginner Category Gap",
      spokeId: "competitors",
      tooltip: {"title": "Competitive Radar", "desc": "Citation share from AI simulations: Yamaha holds 66.7% SOV in the beginner category and 25.0% in basses, Taylor and PRS are tied at 15.4% in acoustics, and PRS holds 12.5% in electrics. Fender/Squier wins the outright majority of resolved simulations overall."},
    },
    {
      id: "spoke-fixes",
      x: 800,
      y: 180,
      r: 74,
      status: "success",
      title: "Action Items",
      titleSize: 14,
      stats: [
        `${FENDER_METRICS.prioritizedFixes.value} Actions`,
        FENDER_METRICS.phaseOneLift.value,
      ],
      meta: "Pilot ➔ $38M to $62M Ent.",
      spokeId: "suggestions",
      tooltip: {"title": "Action Items", "desc": "18 high-impact brand interventions. Compare the Phase 1 Quick-Win ($680K) with the full enterprise portfolio potential ($38M to $62M GMV)."},
    },
    {
      id: "spoke-roadmap",
      x: 800,
      y: 820,
      r: 74,
      status: "success",
      title: "Strategy Roadmap",
      titleSize: 14,
      stats: ["90 Days", "3 Phases"],
      meta: "Buy Box & AI Search Visibility",
      spokeId: "roadmap",
      tooltip: {
        title: "90-Day Portfolio Roadmap",
        desc: "A phased 30-60-90 day plan. Buy Box and AI win baselines load with the canvas read, with a target toward 95% Buy Box retention.",
      },
    },
    {
      id: "hub",
      x: 800,
      y: 500,
      r: 98,
      status: "danger",
      variant: "hub",
      title: "Brand Portfolio",
      stats: [],
      logoSrc: "/image.png",
      meta: "Click for Master View",
      spokeId: "hub",
      tooltip: {"title": "Brand Portfolio Overview", "desc": "Click to open the portfolio overview: 5 brand divisions, the executive briefing, and enterprise commercial sizing."},
    },
];
