import type { CanvasMetric } from "@/lib/canvas-sdk";

/**
 * Canonical names and display values for the compact dashboard signals.
 * Widget category names are intentionally not copied here: the UI resolves
 * them from `spokeData`, so renaming a hub/spoke updates the picker too.
 */
export const FENDER_METRICS = {
  catalogSkus: {
    id: "catalog-skus",
    spokeId: "hub",
    label: "Monitored Electric SKUs",
    value: "See read",
    detail: "Division count loads with the division table",
    tone: "neutral",
    subTab: "Brand Divisions",
    provenance: "live",
  },
  activeOfferCoverage: {
    id: "active-offer-coverage",
    spokeId: "hub",
    label: "Active Amazon Offer Coverage",
    value: "See read",
    detail: "Active offers load with the catalog read",
    tone: "warning",
    subTab: "Executive Briefing",
    provenance: "live",
  },
  buyBoxRetention: {
    id: "buy-box-retention",
    spokeId: "ecommerce",
    label: "Confirmed Amazon 1P Buy Box",
    value: "See read",
    detail: "Amazon 1P share of active offers",
    tone: "danger",
    subTab: "Retail Overview",
    provenance: "live",
  },
  sellerDataCoverage: {
    id: "seller-data-coverage",
    spokeId: "ecommerce",
    label: "Seller Data Harvested",
    value: "See read",
    detail: "Seller rows in the catalog read",
    tone: "warning",
    subTab: "Retail Overview",
    provenance: "live",
  },
  flaggedAsins: {
    id: "flagged-asins",
    spokeId: "ecommerce",
    label: "MAP violations",
    value: "Unavailable",
    detail: "The MAP listing read did not succeed.",
    tone: "warning",
    subTab: "MAP",
    provenance: "live",
  },
  strandedReviews: {
    id: "stranded-reviews",
    spokeId: "ecommerce",
    label: "Stranded Customer Reviews",
    value: "See read",
    detail: "Split across partner bundle pages",
    tone: "danger",
    subTab: "Catalog",
    provenance: "live",
  },
  amazonMapDrift: {
    id: "amazon-map-drift",
    spokeId: "ecommerce",
    label: "Average Amazon Price Drift",
    value: "Unavailable",
    detail: "The live MAP read is not available.",
    tone: "danger",
    subTab: "MAP",
    provenance: "live",
  },
  overallAiWinRate: {
    id: "overall-ai-win-rate",
    spokeId: "aeo",
    label: "Overall AI Win Rate",
    value: "73.3%",
    detail: "55 of 75 resolved simulations",
    tone: "success",
    subTab: "Dual-Index",
    provenance: "live",
  },
  beginnerAiWinRate: {
    id: "beginner-ai-win-rate",
    spokeId: "aeo",
    label: "Beginner AI Win Rate",
    value: "33.3%",
    detail: "Weakest prompt category",
    tone: "danger",
    subTab: "Simulations",
    provenance: "live",
  },
  resolvedSimulations: {
    id: "resolved-simulations",
    spokeId: "aeo",
    label: "Resolved AI Simulations",
    value: "75 / 102",
    detail: "27 calls timed out",
    tone: "warning",
    subTab: "Simulations",
    provenance: "live",
  },
  confirmedHallucinations: {
    id: "confirmed-hallucinations",
    spokeId: "aeo",
    label: "Confirmed Spec Hallucinations",
    value: "See read",
    detail: "Flagged rows are on the Hallucination tab",
    tone: "danger",
    subTab: "Hallucination",
    provenance: "live",
  },
  fenderFindability: {
    id: "fender-findability",
    spokeId: "specs",
    label: "fender.com Product Findability",
    value: "29.2%",
    detail: "21 of 72 pages found",
    tone: "danger",
    subTab: "Catalog Readiness",
    provenance: "live",
  },
  machineReadableSpecs: {
    id: "machine-readable-specs",
    spokeId: "specs",
    label: "Machine-Readable Spec Coverage",
    value: "0%",
    detail: "additionalProperty absent on found pages",
    tone: "danger",
    subTab: "Schema.org",
    provenance: "live",
  },
  missingSchemaFields: {
    id: "missing-schema-fields",
    spokeId: "specs",
    label: "Missing Schema.org Spec Fields",
    value: "See read",
    detail: "Missing-field rows are on the Schema tab",
    tone: "warning",
    subTab: "Schema.org",
    provenance: "live",
  },
  beginnerSovGap: {
    id: "beginner-sov-gap",
    spokeId: "competitors",
    label: "Beginner Category SOV Gap",
    value: "See read",
    detail: "Beginner rows are in the share-of-voice table",
    tone: "danger",
    subTab: "Battlecards",
    provenance: "live",
  },
  strongestCategorySov: {
    id: "strongest-category-sov",
    spokeId: "competitors",
    label: "Strongest Category SOV",
    value: "100%",
    detail: "Amps · 9 of 9 resolved simulations",
    tone: "success",
    subTab: "Battlecards",
    provenance: "live",
  },
  prioritizedFixes: {
    id: "prioritized-fixes",
    spokeId: "suggestions",
    label: "Prioritized Action Items",
    value: "18",
    detail: "Ranked by recovery and visibility impact",
    tone: "warning",
    subTab: "Priority Matrix",
    provenance: "estimate",
  },
  phaseOneLift: {
    id: "phase-one-lift",
    spokeId: "suggestions",
    label: "Recoverable Revenue",
    value: "+$680K",
    detail: "Phase 1 annual · 14 pilot ASINs",
    tone: "success",
    subTab: "ROI",
    provenance: "estimate",
  },
  enterprisePotential: {
    id: "enterprise-potential",
    spokeId: "suggestions",
    label: "Enterprise GMV Potential",
    value: "+$38M to $62M",
    detail: "Annual · full portfolio",
    tone: "success",
    subTab: "ROI",
    provenance: "estimate",
  },
  dayNinetyBuyBoxTarget: {
    id: "day-90-buy-box-target",
    spokeId: "roadmap",
    label: "90-day plan",
    value: "3 phases",
    detail: "MAP, catalog nesting, and estimated lift",
    tone: "success",
    subTab: "30-60-90",
    provenance: "live",
  },
} satisfies Record<string, CanvasMetric>;

export const fenderWidgetMetrics = Object.values(FENDER_METRICS);
