import { fenderCommandCenter } from "@/components/v3/command-center-data";
import { FENDER_METRICS, fenderWidgetMetrics } from "@/components/v3/fender-metrics";
import { fenderGlossary } from "@/components/v3/glossary";
import { spokeData, tourSteps } from "@/components/v3/spoke-data";
import { defineCanvas } from "@/lib/canvas-sdk";

const FOCUS_TARGETS = {
  "hub": { x: 800, y: 500 },
  "aeo": { x: 440, y: 320 },
  "aeo:simulations": { x: 240, y: 200 },
  "aeo:citation": { x: 180, y: 360 },
  "aeo:hallucination": { x: 260, y: 480 },
  "ecommerce": { x: 1160, y: 320 },
  "ecommerce:flagged": { x: 1360, y: 200 },
  "ecommerce:catalog": { x: 1420, y: 360 },
  "ecommerce:map": { x: 1340, y: 480 },
  "specs": { x: 440, y: 680 },
  "specs:schema": { x: 230, y: 720 },
  "specs:a+": { x: 320, y: 870 },
  "competitors": { x: 1160, y: 680 },
  "competitors:battlecards": { x: 1370, y: 720 },
  "competitors:head-to-head": { x: 1280, y: 870 },
  "suggestions": { x: 800, y: 180 },
};

export const fenderCanvasSpec = defineCanvas({
  appearance: "iom",
  commandCenter: fenderCommandCenter,
  glossary: fenderGlossary,
  metricWidgets: {
    metrics: fenderWidgetMetrics,
    defaults: [
      FENDER_METRICS.flaggedAsins.id,
      FENDER_METRICS.confirmedHallucinations.id,
      FENDER_METRICS.phaseOneLift.id,
    ],
    storageKey: "ifai:fender:metric-widgets:v2",
  },
  brand: {
    name: "Fender Brand Intelligence Canvas v3",
    subtitle:
      "FMIC Omnichannel Intelligence · 3,430 Monitored Electric SKUs Across 6 Catalog Divisions (live catalog, updated 2026-09-29)",
    logoSrc: "/icon.png",
    badge: "Enterprise Command",
  },
  filters: [
    { value: "all", label: "Entire FMIC Electric Catalog (3,430 SKUs)", target: "overview" },
    { value: "electrics", label: "Electric Division (Player II, Strat, Tele)", target: "ecommerce" },
    { value: "acoustics", label: "Acoustic & Hybrids (Acoustasonic, Paramount)", target: "competitors" },
    { value: "bass", label: "Bass Division (Precision, Jazz Bass)", target: "specs" },
    { value: "amps", label: "Amps & Digital Audio (Tone Master, Mustang Micro)", target: "aeo" },
    { value: "squier", label: "Squier Entry Tier (Affinity, Classic Vibe)", target: "ecommerce" },
  ],
  tickers: [
    {
      id: "buybox",
      tone: "danger",
      icon: "pulse",
      spokeId: "ecommerce",
      subTab: "flagged",
      label: (
        <>
          Buy Box (Active Offers): <strong>{FENDER_METRICS.buyBoxRetention.value} 1P</strong>{" "}
          (74 of 993 active)
        </>
      ),
    },
    {
      id: "aeo",
      tone: "warning",
      icon: "sparkles",
      spokeId: "aeo",
      subTab: "dual-index",
      label: (
        <>
          AI Win Rate: <strong>{FENDER_METRICS.overallAiWinRate.value}</strong> · Weakest:{" "}
          <strong>Beginner {FENDER_METRICS.beginnerAiWinRate.value}</strong>
        </>
      ),
    },
    {
      id: "opportunity",
      tone: "success",
      icon: "trending",
      spokeId: "suggestions",
      subTab: "roi",
      label: (
        <>
          Lift: <strong>{FENDER_METRICS.phaseOneLift.value} Phase 1</strong> (
          {FENDER_METRICS.enterprisePotential.value} Enterprise)
        </>
      ),
    },
  ],
  search: {
    placeholder: "Search model, ASIN, simulation prompt, partner...",
    matchers: [
      { keywords: ["buy box", "asin", "austin bazaar", "geartree", "amazon", "walmart", "reverb", "map", "leakage", "b0d8", "b0c9"], spokeId: "ecommerce" },
      { keywords: ["aeo", "prompt", "citation", "simulation", "hallucination", "readiness", "humbucker", "radius"], spokeId: "aeo" },
      { keywords: ["spec", "schema", "json-ld", "a+", "matrix", "table", "wood", "frets"], spokeId: "specs" },
      { keywords: ["competitor", "taylor", "prs", "boss", "katana", "yamaha", "pacifica", "gs mini", "spark"], spokeId: "competitors" },
      { keywords: ["roi", "enterprise", "pilot", "lift", "$680k", "$38m", "$50m", "$62m", "$28.4m", "sprint", "retainer"], spokeId: "suggestions" },
      { keywords: ["roadmap", "timeline", "90", "milestone", "resourcing", "managed", "copilot"], spokeId: "roadmap" },
      { keywords: ["hub", "portfolio", "command", "ceo", "joe", "fmic", "executive"], spokeId: "hub" },
    ],
  },
  legend: [
    { status: "danger", label: "Critical / Buy Box Suppression" },
    { status: "warning", label: "At Risk / Review Splintering" },
    { status: "success", label: "On Track / Lift Target" },
  ],
  badges: [
    {
      x: 800,
      y: 315,
      width: 310,
      height: 26,
      text: "🚨 3P BUNDLE SPLINTERING DILUTING TOTAL REVIEW VELOCITY",
    },
  ],
  edges: [
    { x1: 800, y1: 500, x2: 440, y2: 320 },
    { x1: 800, y1: 500, x2: 1160, y2: 320 },
    { x1: 800, y1: 500, x2: 440, y2: 680 },
    { x1: 800, y1: 500, x2: 1160, y2: 680 },
    { x1: 800, y1: 500, x2: 800, y2: 180 },
    { x1: 440, y1: 320, x2: 240, y2: 200 },
    { x1: 440, y1: 320, x2: 180, y2: 360 },
    { x1: 440, y1: 320, x2: 260, y2: 480 },
    { x1: 1160, y1: 320, x2: 1360, y2: 200, kind: "critical" },
    { x1: 1160, y1: 320, x2: 1420, y2: 360, kind: "critical" },
    { x1: 1160, y1: 320, x2: 1340, y2: 480 },
    { x1: 440, y1: 680, x2: 230, y2: 720 },
    { x1: 440, y1: 680, x2: 320, y2: 870 },
    { x1: 1160, y1: 680, x2: 1370, y2: 720 },
    { x1: 1160, y1: 680, x2: 1280, y2: 870 },
  ],
  nodes: [
    {
      id: "sat-prompts",
      x: 240,
      y: 200,
      r: 52,
      status: "danger",
      title: "102 SIMS",
      stats: ["34 Prompts x 3 Engines", "73% Win (of Answered)"],
      meta: "ChatGPT · Perplexity · Gemini",
      spokeId: "aeo",
      subTab: "simulations",
      tooltip: {"title": "Real AI Simulation Battery (Live Run)", "desc": "Ran 34 real prompts across ChatGPT, Perplexity, and Gemini (102 total calls) via live AI-Search API. Of 75 answered calls (27 ChatGPT/Perplexity timeouts excluded): 55 Fender/Squier wins (73.3%), 20 competitor wins (26.7%), 4 unclear, 2 confirmed spec hallucinations."},
    },
    {
      id: "sat-citations",
      x: 180,
      y: 360,
      r: 52,
      status: "danger",
      title: "CITATIONS",
      stats: ["Fender/DTC 50%", "Guitar Press 28%"],
      meta: "Reddit 1% · Amazon 1% (of 74 cited answers)",
      spokeId: "aeo",
      subTab: "citation",
      tooltip: {"title": "AI Citation Ecosystem (Real 34-Prompt Battery)", "desc": "Across 74 answered calls with citations: Fender.com/official Fender pages appeared in 37 (50%), third-party guitar press (Guitar World, MusicRadar, Premier Guitar, etc.) in 21 (28.4%), Reddit in 1 (1.4%), Amazon in 1 (1.4%). Sample size is one real 34-prompt run, not a full historical average."},
    },
    {
      id: "sat-drift",
      x: 260,
      y: 480,
      r: 52,
      status: "warning",
      title: "AI DRIFT",
      stats: [`${FENDER_METRICS.confirmedHallucinations.value} Confirmed Hallucinations`, "Mustang Micro Tubes"],
      meta: "of 6 hallucination-risk answers received",
      spokeId: "aeo",
      subTab: "hallucination",
      tooltip: {"title": "Detected Spec Hallucinations (Real 34-Prompt Battery)", "desc": "Real run flagged 2 of 6 answered hallucination-risk prompts: Perplexity and Gemini both incorrectly implied the Fender Mustang Micro (a headphone amp) has vacuum tube circuitry. Acoustasonic humbucker and Player II 12in radius checks did not reproduce in this run (ChatGPT timed out on those prompts, so untested this cycle)."},
    },
    {
      id: "sat-buybox",
      x: 1360,
      y: 200,
      r: 54,
      status: "danger",
      title: "BUY BOX",
      stats: [`${FENDER_METRICS.buyBoxRetention.value} 1P`, "92.6% Unk"],
      meta: "993 Active Offers",
      spokeId: "ecommerce",
      subTab: "flagged",
      tooltip: {"title": "Buy Box (Active Offers)", "desc": "7.4% Amazon 1P owned on 993 active listings; 92.6% seller data unharvested; 0% confirmed 3P wins."},
    },
    {
      id: "sat-asin",
      x: 1420,
      y: 360,
      r: 54,
      status: "warning",
      title: "ASIN SPLIT",
      stats: [
        `${FENDER_METRICS.flaggedAsins.value} Bundles`,
        `${FENDER_METRICS.strandedReviews.value} Reviews`,
      ],
      meta: "Austin Bazaar / GearTree",
      spokeId: "ecommerce",
      subTab: "catalog",
      tooltip: {"title": "Splintered Bundle ASINs", "desc": "Key partners Austin Bazaar & GearTree hold Brand Registry bundle rights. Splintering reviews forfeits Amazon's Overall Pick badge."},
    },
    {
      id: "sat-map",
      x: 1340,
      y: 480,
      r: 52,
      status: "danger",
      title: "MAP LEAKAGE",
      stats: [
        "-$39.21 Avg",
        `${FENDER_METRICS.flaggedAsins.value} ASINs`,
      ],
      meta: "Amazon · Reverb · Walmart",
      spokeId: "ecommerce",
      subTab: "map",
      tooltip: {"title": "Cross-Marketplace MAP Leakage", "desc": "Starter kit bundles sidestep standalone MAP, prompting automated scrapers on Reverb & Walmart to undercut."},
    },
    {
      id: "sat-schema",
      x: 230,
      y: 720,
      r: 50,
      status: "danger",
      title: "SCHEMA.ORG",
      stats: ["0% Specs", "62 Checked"],
      meta: "additionalProperty Missing",
      spokeId: "specs",
      subTab: "schema",
      tooltip: {"title": "Schema.org Structured Data (Live Sample)", "desc": "Live batch check (19 of ~993 SKUs so far): fender.com product pages found via site search only 36.8% of the time (7/19). Of those found, 0 of 7 have any additionalProperty JSON-LD field, so no machine-readable nut width, fingerboard radius, or pickup config exists for AI engines to read; specs exist only as human-readable HTML tables."},
    },
    {
      id: "sat-tables",
      x: 320,
      y: 870,
      r: 48,
      status: "warning",
      title: "A+ TABLES",
      stats: ["93.3% Amazon", "62 Checked"],
      meta: "Amazon Field Completeness (Live)",
      spokeId: "specs",
      subTab: "a+",
      tooltip: {"title": "Amazon Structured Field Completeness (Live Sample)", "desc": "Live batch check (19 of ~993 SKUs so far): Amazon product_details fields (body/neck material, pickup config, bridge type, scale length, dimensions, etc.) average 97.2% complete. Amazon-side data is strong; fender.com structured data is the real gap."},
    },
    {
      id: "sat-taylor",
      x: 1370,
      y: 720,
      r: 51,
      status: "warning",
      title: "TAYLOR / PRS",
      stats: ["15.4% Taylor", "15.4% PRS"],
      meta: "Acoustics Category (Live SOV)",
      spokeId: "competitors",
      subTab: "battlecards",
      tooltip: {"title": "Taylor & PRS Category Battles (Live AI Simulation Data)", "desc": "Live simulation SOV in acoustics category: Taylor and PRS tied at 15.4% each; Fender/Squier still leads at 61.5% of resolved acoustics sims. Prior 58%/34% figures were unsourced and have been retired."},
    },
    {
      id: "sat-amps",
      x: 1280,
      y: 870,
      r: 48,
      status: "warning",
      title: "AMPS CATEGORY",
      stats: ["100% Fender", "9 of 9 Sims"],
      meta: "No Competitor Wins (Live)",
      spokeId: "competitors",
      subTab: "head-to-head",
      tooltip: {"title": "Digital Amp Ecosystem (Live AI Simulation Data)", "desc": "Live simulation data shows Fender/Squier winning 100% of resolved amps-category AI prompts (9 of 9). No confirmed Boss Katana or Positive Grid Spark wins in current sample; prior 62% SOV claim was unsourced and has been retired."},
    },
    {
      id: "spoke-aeo",
      x: 440,
      y: 320,
      r: 86,
      status: "danger",
      title: spokeData.aeo.navLabel.toUpperCase(),
      titleSize: 14.5,
      stats: [`${FENDER_METRICS.overallAiWinRate.value} Win`, "102 Sims"],
      meta: `Weakest: Beginner ${FENDER_METRICS.beginnerAiWinRate.value}`,
      spokeId: "aeo",
      tooltip: {"title": "Brand AEO Engine & Simulations (Live Data)", "desc": "Real AI win rate: 73.3% of 75 resolved simulations (55 Fender/Squier wins, 27 timeouts excluded). Weakest category is Beginner Electric Guitars at 33.3%. Click to inspect all 102 simulations. Prior 62 Scan/42% Readiness figures were unvalidated placeholders and have been retired."},
    },
    {
      id: "spoke-retail",
      x: 1160,
      y: 320,
      r: 86,
      status: "danger",
      title: spokeData.ecommerce.navLabel.toUpperCase(),
      titleSize: 13.5,
      stats: [`${FENDER_METRICS.buyBoxRetention.value} 1P`, "993 Active"],
      meta: "92.6% Unharvested · 993 Sample",
      spokeId: "ecommerce",
      tooltip: {"title": "Portfolio Retail & Brand Registry", "desc": "Buy Box 7.4% 1P of 993 active offers (2,437 unharvested / no active offer). Brand Registry consolidation with Austin Bazaar & GearTree across the Monitored ASIN Sample."},
    },
    {
      id: "spoke-specs",
      x: 440,
      y: 680,
      r: 78,
      status: "warning",
      title: spokeData.specs.navLabel.toUpperCase(),
      titleSize: 13.5,
      stats: [
        `${FENDER_METRICS.fenderFindability.value} Found`,
        `${FENDER_METRICS.machineReadableSpecs.value} Specs`,
      ],
      meta: "Live Sample: 62 of 993",
      spokeId: "specs",
      tooltip: {"title": "Catalog Spec Readiness (Live Sample, Growing Hourly)", "desc": "Live batch check of 72 of ~993 active-offer SKUs so far. fender.com product page found via site search only 29.2% of the time (21 of 72); of those found, 0% have any Schema.org additionalProperty spec fields. Amazon-side structured fields average 91.7% complete. This bubble was previously an unsourced 34% completeness claim with no backing data; it is now computed by the fender_spec_readiness_audit wrench and refreshed hourly."},
    },
    {
      id: "spoke-competitors",
      x: 1160,
      y: 680,
      r: 78,
      status: "danger",
      title: spokeData.competitors.navLabel.toUpperCase(),
      titleSize: 13,
      stats: ["Yamaha 66.7%", "5 Rivals (Live)"],
      meta: "Beginner Category Gap",
      spokeId: "competitors",
      tooltip: {"title": "Brand Competitive Radar", "desc": "Live citation share from real AI simulations: Yamaha 66.7% SOV in beginner category, Yamaha 25.0% in basses, Taylor 15.4% and PRS 15.4% (tied) in acoustics, PRS 12.5% in electrics. Fender/Squier wins the outright majority of resolved simulations overall."},
    },
    {
      id: "spoke-fixes",
      x: 800,
      y: 180,
      r: 74,
      status: "success",
      title: spokeData.suggestions.navLabel.toUpperCase(),
      titleSize: 14,
      stats: [
        `${FENDER_METRICS.prioritizedFixes.value} Fixes`,
        FENDER_METRICS.phaseOneLift.value,
      ],
      meta: "Pilot ➔ $38M to $62M Ent.",
      spokeId: "suggestions",
      tooltip: {"title": "Portfolio Suggestion Engine", "desc": "18 high-impact brand interventions: Phase 1 Quick-Win ($680K) vs Full Enterprise Portfolio Potential ($38M to $62M GMV)."},
    },
    {
      id: "hub",
      x: 800,
      y: 500,
      r: 98,
      status: "danger",
      variant: "hub",
      title: "BRAND PORTFOLIO",
      stats: [],
      logoSrc: "/image.png",
      meta: "Click for Master View",
      spokeId: "hub",
      tooltip: {"title": "Master Brand Portfolio Core", "desc": "Click to open Master Portfolio Command View (5 Brand Divisions, Executive Briefing & Enterprise Commercial Sizing)."},
    },
  ],
  spokes: spokeData,
  focusTargets: FOCUS_TARGETS,
  tour: tourSteps,
});
