import type { CanvasMetric } from "@/lib/canvas-sdk";

/**
 * Canonical names and display values for the compact dashboard signals.
 * Widget category names are intentionally not copied here: the UI resolves
 * them from `spokeData`, so renaming a hub/spoke updates the picker too.
 */
export const FENDER_METRICS = {
  catalogSkus: {
    id: "catalog-skus",
    spokeId: "hub",
    label: "Monitored Electric SKUs",
    value: "3,430",
    detail: "6 divisions",
    tone: "neutral",
    subTab: "Brand Divisions",
    provenance: "live",
  },
  activeOfferCoverage: {
    id: "active-offer-coverage",
    spokeId: "hub",
    label: "Active Amazon Offer Coverage",
    value: "29.0%",
    detail: "993 of 3,430 monitored SKUs",
    tone: "warning",
    subTab: "Executive Briefing",
    provenance: "live",
  },
  buyBoxRetention: {
    id: "buy-box-retention",
    spokeId: "ecommerce",
    label: "Confirmed Amazon 1P Buy Box",
    value: "7.4%",
    detail: "74 of 993 active offers",
    tone: "danger",
    subTab: "Flagged ASINs",
    provenance: "live",
  },
  sellerDataCoverage: {
    id: "seller-data-coverage",
    spokeId: "ecommerce",
    label: "Seller Data Harvested",
    value: "2.2%",
    detail: "74 of 3,430 SKUs",
    tone: "warning",
    subTab: "Flagged ASINs",
    provenance: "live",
  },
  flaggedAsins: {
    id: "flagged-asins",
    spokeId: "ecommerce",
    label: "Flagged ASINs",
    value: "14",
    detail: "Bundle leakage and review dilution",
    tone: "danger",
    subTab: "Flagged ASINs",
    provenance: "live",
  },
  strandedReviews: {
    id: "stranded-reviews",
    spokeId: "ecommerce",
    label: "Stranded Customer Reviews",
    value: "2,420+",
    detail: "Split across partner bundle pages",
    tone: "danger",
    subTab: "Catalog",
    provenance: "live",
  },
  amazonMapDrift: {
    id: "amazon-map-drift",
    spokeId: "ecommerce",
    label: "Average Amazon Price Drift",
    value: "−$77.58",
    detail: "Across 118 active-offer SKUs",
    tone: "danger",
    subTab: "MAP",
    provenance: "live",
  },
  overallAiWinRate: {
    id: "overall-ai-win-rate",
    spokeId: "aeo",
    label: "Overall AI Win Rate",
    value: "73.3%",
    detail: "55 of 75 resolved simulations",
    tone: "success",
    subTab: "Dual-Index",
    provenance: "live",
  },
  beginnerAiWinRate: {
    id: "beginner-ai-win-rate",
    spokeId: "aeo",
    label: "Beginner AI Win Rate",
    value: "33.3%",
    detail: "Weakest prompt category",
    tone: "danger",
    subTab: "Simulations",
    provenance: "live",
  },
  resolvedSimulations: {
    id: "resolved-simulations",
    spokeId: "aeo",
    label: "Resolved AI Simulations",
    value: "75 / 102",
    detail: "27 calls timed out",
    tone: "warning",
    subTab: "Simulations",
    provenance: "live",
  },
  confirmedHallucinations: {
    id: "confirmed-hallucinations",
    spokeId: "aeo",
    label: "Confirmed Spec Hallucinations",
    value: "2",
    detail: "Of 6 hallucination-risk answers received",
    tone: "danger",
    subTab: "Hallucination",
    provenance: "live",
  },
  fenderFindability: {
    id: "fender-findability",
    spokeId: "specs",
    label: "fender.com Product Findability",
    value: "29.2%",
    detail: "21 of 72 pages found",
    tone: "danger",
    subTab: "Catalog Readiness",
    provenance: "live",
  },
  machineReadableSpecs: {
    id: "machine-readable-specs",
    spokeId: "specs",
    label: "Machine-Readable Spec Coverage",
    value: "0%",
    detail: "additionalProperty absent on found pages",
    tone: "danger",
    subTab: "Schema.org",
    provenance: "live",
  },
  missingSchemaFields: {
    id: "missing-schema-fields",
    spokeId: "specs",
    label: "Missing Schema.org Spec Fields",
    value: "6",
    detail: "Core technical attributes to publish",
    tone: "warning",
    subTab: "Schema.org",
    provenance: "live",
  },
  beginnerSovGap: {
    id: "beginner-sov-gap",
    spokeId: "competitors",
    label: "Beginner Category SOV Gap",
    value: "−50 pts",
    detail: "Yamaha 66.7% vs Fender/Squier 16.7%",
    tone: "danger",
    subTab: "Battlecards",
    provenance: "live",
  },
  strongestCategorySov: {
    id: "strongest-category-sov",
    spokeId: "competitors",
    label: "Strongest Category SOV",
    value: "100%",
    detail: "Amps · 9 of 9 resolved simulations",
    tone: "success",
    subTab: "Battlecards",
    provenance: "live",
  },
  prioritizedFixes: {
    id: "prioritized-fixes",
    spokeId: "suggestions",
    label: "Prioritized Action Items",
    value: "18",
    detail: "Ranked by recovery and visibility impact",
    tone: "warning",
    subTab: "Priority Matrix",
    provenance: "estimate",
  },
  phaseOneLift: {
    id: "phase-one-lift",
    spokeId: "suggestions",
    label: "Recoverable Revenue",
    value: "+$680K",
    detail: "Phase 1 annual · 14 pilot ASINs",
    tone: "success",
    subTab: "ROI",
    provenance: "estimate",
  },
  enterprisePotential: {
    id: "enterprise-potential",
    spokeId: "suggestions",
    label: "Enterprise GMV Potential",
    value: "+$38M to $62M",
    detail: "Annual · full portfolio",
    tone: "success",
    subTab: "ROI",
    provenance: "estimate",
  },
  dayNinetyBuyBoxTarget: {
    id: "day-90-buy-box-target",
    spokeId: "roadmap",
    label: "Day 90 Buy Box Target",
    value: "95%+",
    detail: "Target · baseline 7.4%",
    tone: "success",
    subTab: "KPI Target",
    provenance: "estimate",
  },
} satisfies Record<string, CanvasMetric>;

export const fenderWidgetMetrics = Object.values(FENDER_METRICS);
